<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNS2MiXB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNS2MiXB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNS2MiXB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNS2MiXB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNS2MiXB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NS2MiXB',
    'container.build_id' => 'd5081da9',
    'container.build_time' => 1576271930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNS2MiXB');
