<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Room extends \App\Entity\Room implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'seats', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'seats_occupied', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'map_pose', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'id_code', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'presentations'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'seats', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'seats_occupied', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'map_pose', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'id_code', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'presentations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Room $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeats(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeats', []);

        return parent::getSeats();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeats(?int $seats): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeats', [$seats]);

        return parent::setSeats($seats);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeatsOccupied(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeatsOccupied', []);

        return parent::getSeatsOccupied();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeatsOccupied(?int $seats_occupied): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeatsOccupied', [$seats_occupied]);

        return parent::setSeatsOccupied($seats_occupied);
    }

    /**
     * {@inheritDoc}
     */
    public function getMapPose(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMapPose', []);

        return parent::getMapPose();
    }

    /**
     * {@inheritDoc}
     */
    public function setMapPose(?int $map_pose): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMapPose', [$map_pose]);

        return parent::setMapPose($map_pose);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCode', []);

        return parent::getIdCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCode(?string $id_code): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCode', [$id_code]);

        return parent::setIdCode($id_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentations', []);

        return parent::getPresentations();
    }

    /**
     * {@inheritDoc}
     */
    public function addPresentation(\App\Entity\Presentation $presentation): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPresentation', [$presentation]);

        return parent::addPresentation($presentation);
    }

    /**
     * {@inheritDoc}
     */
    public function removePresentation(\App\Entity\Presentation $presentation): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePresentation', [$presentation]);

        return parent::removePresentation($presentation);
    }

}
