/// Flutter icons GuideasyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GuideasyIcons
///      fonts:
///       - asset: fonts/GuideasyIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class GuideasyIcons {
  GuideasyIcons._();

  static const _kFontFam = 'GuideasyIcons';

  static const IconData room = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData coffee = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData stairs = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData concierge_bell_solid = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData lostandfound = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData elevator = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData vending_machine = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData female = const IconData(0xf182, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xf183, fontFamily: _kFontFam);
  static const IconData wheelchair = const IconData(0xf193, fontFamily: _kFontFam);
}
